name: nexus-subtheme
recipe: drupal8
config:
  php: '7.2'
  via: apache
  webroot: web
  database: mariadb:10.3.16
proxy:
  phpmyadmin:
    - pma-nexus-subtheme.lndo.site
services:
  node:
    type: node
    globals:
      gulp-cli: "latest"
  phpmyadmin:
    type: phpmyadmin
tooling:
  drupal:
    cmd: /app/vendor/bin/drupal --root=/app/web
  drush:
    cmd: /app/vendor/bin/drush
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
